project:
  type: website
  output-dir: docs

website:
  title: "Team xxxxx"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Team Members
        href: team_members.qmd
            
    tools:
      - icon: github

  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true

format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

